output_path = "./results"
gpu = 0
use_pretrained = true

# 使用するモデルの名前
#model_name = "EfficientNetV2"
model_name = "SEResNeXt"
#model_name = "VisionTransformer"
#model_name = "DeiT"

[parameters]
num_epoches = 50
batch_size = 48

# 入力画像サイズ: (height, width)
input_size = [224, 224]

[optimizer]
lr = 1e-4